added code to copy binnaries (with their deps) and fsck

diff --git a/init b/init
--- a/init
+++ b/init
@@ -5,6 +5,50 @@ rescue_shell() {
     exec sh
 }
 
+check_filesystem() {
+    # most of code coming from /etc/init.d/fsck
+
+    local fsck_opts= check_extra= RC_UNAME=$(uname -s)
+
+    # FIXME : get_bootparam forcefsck
+    if [ -e /forcefsck ]; then
+	fsck_opts="$fsck_opts -f"
+	check_extra="(check forced)"
+    fi
+
+    echo "Checking local filesystem $check_extra : $1"
+
+    if [ "$RC_UNAME" = Linux ]; then
+	fsck_opts="$fsck_opts -C0 -T"
+    fi
+
+    trap : INT QUIT
+
+    # using our own fsck, not the builtin one from busybox
+    /sbin/fsck -p $fsck_opts $1
+
+    case $? in
+	0)      return 0;;
+	1)      echo "Filesystem repaired"; return 0;;
+	2|3)    if [ "$RC_UNAME" = Linux ]; then
+		    echo "Filesystem repaired, but reboot needed"
+		    reboot -f
+		else
+		    rescue_shell "Filesystem still have errors; manual fsck required"
+		fi;;
+	4)      if [ "$RC_UNAME" = Linux ]; then
+		    rescue_shell "Fileystem errors left uncorrected, aborting"
+		else
+		    echo "Filesystem repaired, but reboot needed"
+		    reboot
+		fi;;
+	8)      echo "Operational error"; return 0;;
+	12)     echo "fsck interrupted";;
+	*)      echo "Filesystem couldn't be fixed";;
+    esac
+    rescue_shell
+}
+
 # Mount the /proc and /sys filesystems.
 mount -t devtmpfs none /dev
 mount -t proc none /proc
@@ -15,7 +59,12 @@ echo "This script just mounts and boots the rootfs and maybe fscks it, nothing e
 
 # Mount the root filesystem.
 # 8ba7f391-11cd-45bb-82f0-b65e9bf7533a -> root
-mount -o ro $(findfs UUID=8ba7f391-11cd-45bb-82f0-b65e9bf7533a) /mnt/root || rescue_shell
+
+ROOTFS=$(findfs UUID=8ba7f391-11cd-45bb-82f0-b65e9bf7533a)
+
+check_filesystem $ROOTFS
+
+mount -o ro $ROOTFS /mnt/root || rescue_shell
 
 # Clean up.
 umount /proc
